### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by emans** [snargledorf/PicassoSharp#1]
I've been trying to compile the solution you provide but it simply does not work. Did you forgot some files in your git push? Could you check this up?

Thanks.

**Comment by snargledorf** [comment]
What error(s) do you get when attempting to compile?

Edit: I have found the issue. Will upload the missing code

**Comment by snargledorf** [comment]
I have uploaded the fixed source. Please verify that the solution compiles as of commit 578f31f52245c742e16cafccf61e2853559b9f33

**Comment by emans** [comment]
Hi, yes it works perfectly. Thanks a lot.

**Comment by snargledorf** [comment]
No problem. Thanks for bringing it to my attention.
